baseURL : 'https://www.rushui.net/'
languageCode : 'en-us'
title : '如水网'
theme : "rs"
markup:
  highlight:
   linenos: true
   hl_inline: false
   anchorLineNos: false
   lineNumbersInTable: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
taxonomies:
  tag: tags
  category: categories
sectionPagesMenu: "main"
copyright: "©2009-2023  "
params:
  page_view_conter: true
  announcement: "<strong>如水网</strong>新版本上线了！"
  colors: ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"]
  record: "沪ICP备12030997号-4"
  tongji: '<script>var _hmt=_hmt||[];(function(){var hm=document.createElement("script");hm.src="https://hm.baidu.com/hm.js?5bba6d5be6c8ba53c5998abcc26ed7db";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm,s)})();</script>'
menu:
  main:
  - name: 文章
    identifier: posts
    url: /posts/
    weight: 1
  - name: 项目
    identifier: project
    weight: 2
    url: /project/
  - name: 关于
    identifier: about
    weight: 4
    url: "/about/"
  - name: 个人介绍
    parent: about
    weight: 1
    url: "/about/me/"
  - name: 支付方式
    parent: about
    weight: 2
    url: "/about/pay/"